version: "3"

services:
  flask-web:
    build: ./
    working_dir: /app
    command: /bin/sh -c docker-scripts/build_flask.sh
    ports:
      - "5000:5000"
    volumes:
      - "./.venv:/.venv"

networks:
  default:
    driver: bridge
