version: "3"

services:
  flask-web:
    build: ./flask-web
    command: /bin/sh -c .docker-scripts/build_flask.sh
    ports:
      - "5000:5000"
    expose:
      - "8001"
    volumes:
      - "./flask-web:/app"
  mongodb:
    image: mongo:3.6.6-jessie
    command: mongod
    volumes:
      - "./.services/mongodb/data/db:/data/db"
    ports:
      - "27017:27017"
  nginx:
    image: nginx:1.14
    volumes:
      - ./nginx/flask-web-nginx.conf:/etc/nginx/conf.d/flask-web-nginx.conf

    links:
      - flask-web
    ports:
      - "8000:8000"

networks:
  default:
    driver: bridge
