version: "3"

services:
  flask-web:
    build: ./
    command: /bin/sh -c .docker-scripts/build_flask.sh
    ports:
      - "5000:5000"
    volumes:
      - "./:/app"
  mongodb:
    image: mongo:3.6.6-jessie
    command: mongod
    volumes:
      - "./.services/mongodb/data/db:/data/db"
    ports:
      - "27017:27017"


networks:
  default:
    driver: bridge
